In [54]:
import numpy as np  #import of numpy & Assign alias np

In [56]:
a= np.array([1,2,3,4,5])  #create simple array
print(a)

[1 2 3 4 5]


In [58]:
print("shape of al{}",format(a.shape))  #return the shape of array

shape of al{} (5,)


In [64]:
print("Size :",format(a.size))  #return size of array
print(f"dtype {a.dtype}")       #return datatype of array
print(f"itemsize {a.itemsize}")  #return itemsize of array
print(f"data{a.data}")          #return data of array

Size : 5
dtype int64
itemsize 8
data<memory at 0x7f19b2329ac0>


In [53]:
a = np.array([1,2,3,4,5,6])  #define single array
b = np.array([[7,8],[9,10]])  #define two dimension array
print(a)         #print single array
print(b)         #print two dimention array

[1 2 3 4 5 6]
[[ 7  8]
 [ 9 10]]


In [18]:
slicedArr = a[2:]   #give sliced the array 
print(slicedArr)

[3 4 5 6]


In [19]:
sum_of_a = np.sum(a)  #return sum of digit all the array
print(sum_of_a)

21


In [32]:
m1 = np.array([[1,2],[3,4]])  #used for matrix multipication for 2 dimantion array
m2 = np.array([[5,6],[7,8]])
mul = np.dot(m1,m2)            #1,2  * 5,6
print(mul)                     #3,4    7,8

[[19 22]
 [43 50]]


In [36]:
subM = np.subtract(m2,m1)     # used for subtraction of two array
print(subM)

[[4 4]
 [4 4]]


In [37]:
addM = np.add(m2,m1)         # used for addition of two array
print(addM)

[[ 6  8]
 [10 12]]


In [38]:
m3 = np.array([1,2,3,4,5,6,7,8,9])     # used for resharpe of the array 3*3
print(m3)
re = m3.reshape(3,3)
print(re)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print("Maximum of m3 is = ",max(m3))  # return maximum value from m3 array
print("Maximum of m3 is = ",min(m3))   # return  minimum value from m3 array
print("Maximum of m3 is = ",m3.max())   
print("Minimum of m3 is = ",m3.min())

Maximum of m3 is =  9
Maximum of m3 is =  1
Maximum of m3 is =  9
Minimum of m3 is =  1


In [25]:
print("Maximum in row is = ", re.max(axis=1))  #return maximum value from re array as row wise
print("Minimum in col is = ", re.min(axis=0))  #return minimum value from re array as col wise

Maximum in row is =  [3 6 9]
Minimum in col is =  [1 2 3]


In [26]:
m4 = np.array([[4,9,25],[36,49,64]])
print(m4)
print(np.sqrt(m4))  #return squre root of array m4
print("Standard deviation:",np.std(m4))  #return standard deviation of array m4

[[ 4  9 25]
 [36 49 64]]
[[2. 3. 5.]
 [6. 7. 8.]]
Standard deviation: 21.16141667175323


In [27]:
v = np.vstack((m1,m2))   #used to print the array in vertically
print(v)
h = np.hstack((m1,m2))     #used to print the array in horizontally
print(h)  

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [28]:
arr = np.arange(0,20,2,float)       #used to assign array from 0 to 20 in between gap
print(arr)
print("data type = ", arr.dtype)    #used to display the datatype of array

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
data type =  float64


In [29]:
arr1 = np.linspace(0,20,5)  #Create array from 0 to 20 with 3 value
print(arr1)
print(arr1.dtype)

[ 0.  5. 10. 15. 20.]
float64


In [50]:
d1=np.array([[1,2],[3,4]])    #transform the array
h=np.hstack(d1)
v=np.vstack(d1) 
ht = h.T
vt = v.T
print(ht)
print(vt)

[1 2 3 4]
[[1 3]
 [2 4]]


In [40]:
a=np.array([1,2,3,4,5,6,7,8])   #define array
print(a)

[1 2 3 4 5 6 7 8]


In [41]:
for i in np.nditer(a):  #print the element with using for loop
    print("ele :",i)

ele : 1
ele : 2
ele : 3
ele : 4
ele : 5
ele : 6
ele : 7
ele : 8


In [42]:
hNew=np.hsplit(a,2)
print(hNew)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [43]:
arr=np.array([23,34,45,67])  
print("Sqrt: ",np.sqrt(arr))   #return squre root of each array
print("Exp: ",np.exp(arr))     #return exponentials of each element
print("Sin: ",np.sin(arr))     #return sin of each element
print("Cos: ",np.cos(arr))     #return cos of each element
print("Log: ",np.log(arr))     #return log of each element
print("Sum: ",np.sum(arr))     #return sum of each element
print("Std: ",np.std(arr))     #return standard deviation of array 

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [47]:
from scipy import stats as st
print("mean:",np.mean(arr))   #return mean value of array
print("mean:",np.median(arr))  #return median value of array
print("mean:",st.mode(arr))   #retun mode value

mean: 42.25
mean: 39.5
mean: ModeResult(mode=array([23]), count=array([1]))
